In [1]:
import pandas as pd

# 엑셀 파일 읽기
df = pd.read_excel('(0203최종_2)merged_final_result.xlsx')  # 파일명을 올바르게 지정하세요.

# 5열 이후에 결측치가 있는 행들 필터링
df_with_missing = df[df.iloc[:, 4:].isnull().any(axis=1)]

# 필터링된 데이터에서 고유한 1열, 2열, 3열, 4열 조합 추출
unique_combinations = df_with_missing[['승차_호선', '승차_역', '하차_호선', '하차_역']].drop_duplicates()

# 고유한 조합 출력
unique_combinations

# 필요하다면 결과를 엑셀 파일로 저장하는 코드도 추가할 수 있습니다.
# unique_combinations.to_excel('unique_combinations_with_missing.xlsx', index=False)

       승차_호선 승차_역 하차_호선 하차_역
123750   NaN  NaN   NaN  NaN

In [9]:
unique_combinations.to_excel('unique_combinations_with_missing.xlsx', index=False)

In [4]:
import pandas as pd

# 엑셀 파일 읽기
df = pd.read_excel('merged_final_result.xlsx')  # 파일명을 올바르게 지정하세요.

# 결측치가 있는 행들을 필터링하여 새로운 DataFrame 생성
df_with_missing = df[df.isnull().any(axis=1)]

# 새로운 DataFrame 출력
df_with_missing

# 필요한 경우, 결과를 엑셀로 저장할 수도 있습니다.
# df_with_missing.to_excel('missing_values_rows.xlsx', index=False)

,승차_호선,승차_역,하차_호선,하차_역,20230331,20230430,20230531,20230630,20230731,20230831,...,도착지_2024년 03월,도착지_2024년 04월,도착지_2024년 05월,도착지_2024년 06월,도착지_2024년 07월,도착지_2024년 08월,도착지_2024년 09월,도착지_2024년 10월,도착지_2024년 11월,도착지_2024년 12월
240,1호선,가산디지털단지,1호선,간석,0,0,0,0,0,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
248,1호선,가산디지털단지,1호선,도원,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
249,1호선,가산디지털단지,1호선,도화,0,0,0,0,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
252,1호선,가산디지털단지,1호선,동암,0,0,0,0,10,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
253,1호선,가산디지털단지,1호선,동인천,0,0,0,0,4,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123766,인천지하철 2호선,검암,김포골드라인,김포공항,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124743,인천지하철 2호선,마전,김포골드라인,김포공항,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125738,인천지하철 2호선,서구청,김포골드라인,김포공항,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126702,인천지하철 2호선,석바위시장,김포골드라인,김포공항,0,0,1,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128079,인천지하철 2호선,완정,김포골드라인,김포공항,0,1,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN